---
# Kube-scheduler setup

- name: kube-scheduler | ensure k8s certs and manifests directories exist
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - "{{ k8s_kubelet_manifests_dir }}"
    - "{{ k8s_certs_dir }}"
    - "{{ k8s_kube_scheduler_dir }}"

- name: kube-scheduler | ensure the node certs are present
  copy:
    src: "{{ item }}"
    dest: "{{ k8s_certs_dir }}"
    force: no
  with_items:
    - "{{ k8s_ssl_scheduler_path }}/{{ k8s_ssl_config['scheduler']['cert_name'] }}"
    - "{{ k8s_ssl_scheduler_path }}/{{ k8s_ssl_config['scheduler']['key_name'] }}"

- name: kube-scheduler | install kube-scheduler kubeconfig file
  template:
    src: "{{ k8s_template_dir }}/generate_yaml_template.j2"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items:
    - { yaml: "{{ k8s_scheduler_kubeconfig }}", dest: "{{ k8s_kube_scheduler_kubeconfig }}" }

- name: kube-scheduler | install kube-scheduler manifest
  template:
    src: "{{ k8s_template_dir }}/generate_yaml_template.j2"
    dest: "{{ k8s_kubelet_manifests_dir }}/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
    backup: no
  with_items:
    - { yaml: "{{ k8s_kube_scheduler }}", dest: "kube-scheduler.yml" }
